/* components/Icon/Icon.jsx */
import { createElement, memo } from 'react';
import {
  FaBell, FaBookOpen, FaBrain, FaCheck, FaChevronDown, FaChevronLeft,
  FaChevronRight, FaCircle, FaClock, FaEnvelope, FaExclamationTriangle,
  FaEye, FaEyeSlash, FaFileLines, FaFilePdf, FaFire, FaFlask,
  FaGraduationCap, FaHeart, FaHome, FaLayerGroup, FaLink, FaLock,
  FaMagnifyingGlass, FaMedal, FaMicrophone, FaMicrophoneSlash,
  FaMoon, FaPaperPlane, FaPenToSquare, FaPlay, FaPlus, FaQuestionCircle,
  FaRightFromBracket, FaRocket, FaSeedling, FaShieldHalved, FaSpinner,
  FaStar, FaSun, FaThumbsUp, FaTrophy, FaUser, FaUserGraduate,
  FaUsers, FaVolumeHigh, FaVolumeXmark, FaXmark, FaBars, FaCircleCheck,
  FaCircleXmark, FaDownload, FaArrowRight, FaArrowLeft, FaArrowUp,
  FaCrown, FaLightbulb, FaBookmark, FaShare, FaEllipsis, FaGear,
  FaBullhorn, FaComment, FaUserPlus, FaClipboardCheck, FaChartLine,
  FaHeadset, FaMessage, FaCircleInfo, FaUserPen, FaFileContract,
  FaScrewdriverWrench, FaFaceSmile, FaCapsules, FaDna, FaMicroscope,
  FaCamera, FaTrash, FaRightToBracket, FaIdCard, FaKey, FaCalendar,
  FaCircleCheck as FaCheckCircle, FaStopwatch, FaRotate, FaHand,
  FaTriangleExclamation, FaDoorOpen, FaDoorClosed, FaCircle as FaCircleDot,
  FaBookOpenReader, FaAtom, FaImage, FaTag, FaGaugeHigh, FaHandHoldingHeart,
  FaCreditCard, FaUnlock, FaRoute, FaSpellCheck, FaEnvelopeCircleCheck,
  FaUserCheck, FaGlobe, FaXTwitter, FaLinkedinIn, FaInstagram,
  FaLocationDot, FaListCheck, FaKeyboard, FaFlagCheckered,
} from 'react-icons/fa6';

const ICON_MAP = {
  bell: FaBell, 'book-open': FaBookOpen, brain: FaBrain, check: FaCheck,
  'chevron-down': FaChevronDown, 'chevron-left': FaChevronLeft,
  'chevron-right': FaChevronRight, circle: FaCircleDot, clock: FaClock,
  envelope: FaEnvelope, 'exclamation-triangle': FaTriangleExclamation,
  eye: FaEye, 'eye-slash': FaEyeSlash, 'file-lines': FaFileLines,
  'file-pdf': FaFilePdf, fire: FaFire, flask: FaFlask,
  'graduation-cap': FaGraduationCap, heart: FaHeart, home: FaHome,
  'layer-group': FaLayerGroup, link: FaLink, lock: FaLock,
  'magnifying-glass': FaMagnifyingGlass, medal: FaMedal,
  microphone: FaMicrophone, 'microphone-slash': FaMicrophoneSlash,
  moon: FaMoon, 'paper-plane': FaPaperPlane, 'pen-to-square': FaPenToSquare,
  play: FaPlay, plus: FaPlus, 'question-circle': FaQuestionCircle,
  'right-from-bracket': FaRightFromBracket, rocket: FaRocket,
  seedling: FaSeedling, 'shield-halved': FaShieldHalved, spinner: FaSpinner,
  star: FaStar, sun: FaSun, 'thumbs-up': FaThumbsUp, trophy: FaTrophy,
  user: FaUser, 'user-graduate': FaUserGraduate, users: FaUsers,
  'volume-high': FaVolumeHigh, 'volume-xmark': FaVolumeXmark, xmark: FaXmark,
  bars: FaBars, 'circle-check': FaCheckCircle, 'circle-xmark': FaCircleXmark,
  download: FaDownload, 'arrow-right': FaArrowRight, 'arrow-left': FaArrowLeft,
  'arrow-up': FaArrowUp, crown: FaCrown, lightbulb: FaLightbulb,
  bookmark: FaBookmark, share: FaShare, ellipsis: FaEllipsis, gear: FaGear,
  bullhorn: FaBullhorn, comment: FaComment, 'user-plus': FaUserPlus,
  'clipboard-check': FaClipboardCheck, 'chart-line': FaChartLine,
  headset: FaHeadset, message: FaMessage, 'circle-info': FaCircleInfo,
  'user-pen': FaUserPen, 'file-contract': FaFileContract,
  'screwdriver-wrench': FaScrewdriverWrench, 'face-smile': FaFaceSmile,
  capsules: FaCapsules, dna: FaDna, microscope: FaMicroscope,
  camera: FaCamera, trash: FaTrash, 'right-to-bracket': FaRightToBracket,
  'id-card': FaIdCard, key: FaKey, calendar: FaCalendar,
  'check-circle': FaCheckCircle, stopwatch: FaStopwatch, rotate: FaRotate,
  hand: FaHand, 'door-open': FaDoorOpen, 'door-closed': FaDoorClosed,
  'book-open-reader': FaBookOpenReader, atom: FaAtom, image: FaImage,
  tag: FaTag, 'gauge-high': FaGaugeHigh,
  'hand-holding-heart': FaHandHoldingHeart, 'credit-card': FaCreditCard,
  unlock: FaUnlock, route: FaRoute, 'spell-check': FaSpellCheck,
  'envelope-circle-check': FaEnvelopeCircleCheck, 'user-check': FaUserCheck,
  globe: FaGlobe, 'x-twitter': FaXTwitter, linkedin: FaLinkedinIn,
  instagram: FaInstagram, 'location-dot': FaLocationDot,
  'list-check': FaListCheck, keyboard: FaKeyboard,
  'flag-checkered': FaFlagCheckered,
  'arrow-trend-up': FaChartLine, 'check-double': FaCheckCircle,
  'rotate-right': FaRotate, 'clipboard-list': FaClipboardCheck,
  'fa-trophy': FaTrophy, 'fa-fire': FaFire, 'fa-star': FaStar,
  'fa-book-open-reader': FaBookOpenReader, 'fa-rotate': FaRotate,
  'fa-bullhorn': FaBullhorn, 'fa-triangle-exclamation': FaTriangleExclamation,
  'fa-heart': FaHeart, 'fa-comment': FaComment, 'fa-user-plus': FaUserPlus,
  'fa-layer-group': FaLayerGroup, 'fa-file-pdf': FaFilePdf,
  'fa-book-open': FaBookOpen, 'fa-clipboard-check': FaClipboardCheck,
  'fa-crown': FaCrown, 'fa-medal': FaMedal,
  'fa-hand-holding-heart': FaHandHoldingHeart, 'fa-credit-card': FaCreditCard,
  'fa-lock': FaLock, 'fa-unlock': FaUnlock, 'fa-chart-line': FaChartLine,
  'fa-flask': FaFlask, 'fa-headset': FaHeadset, 'fa-message': FaMessage,
  'fa-rocket': FaRocket, 'fa-circle-check': FaCheckCircle,
  'fa-clock': FaClock, 'fa-download': FaDownload,
  'fa-envelope-circle-check': FaEnvelopeCircleCheck,
  'fa-right-to-bracket': FaRightToBracket, 'fa-shield-halved': FaShieldHalved,
  'fa-user-pen': FaUserPen, 'fa-file-lines': FaFileLines,
  'fa-spell-check': FaSpellCheck, 'fa-pen': FaPenToSquare,
  'fa-pen-to-square': FaPenToSquare, 'fa-route': FaRoute,
  'fa-circle-xmark': FaCircleXmark, 'fa-file-contract': FaFileContract,
  'fa-screwdriver-wrench': FaScrewdriverWrench, 'fa-users': FaUsers,
  'fa-face-smile': FaFaceSmile, 'fa-arrow-trend-up': FaChartLine,
  'fa-check-double': FaCheckCircle, 'fa-rotate-right': FaRotate,
  'fa-clipboard-list': FaClipboardCheck, 'fa-bell': FaBell,
};

const Icon = memo(function Icon({ name, size, className, ...props }) {
  const Component = ICON_MAP[name];
  if (!Component) return null;
  return createElement(Component, {
    size: size || undefined,
    className: className || undefined,
    ...props,
  });
});

export default Icon;
export { ICON_MAP };
