 /* components/Icon/Icon.jsx */
import { createElement, memo } from 'react';
import {
  FaBell,
  FaBookOpen,
  FaBrain,
  FaCheck,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaCircle,
  FaClock,
  FaEnvelope,
  FaEye,
  FaEyeSlash,
  FaFileLines,
  FaFilePdf,
  FaFire,
  FaFlask,
  FaGraduationCap,
  FaHeart,
  FaHouse,
  FaLayerGroup,
  FaLink,
  FaLock,
  FaMagnifyingGlass,
  FaMedal,
  FaMicrophone,
  FaMicrophoneSlash,
  FaMoon,
  FaPenToSquare,
  FaPlus,
  FaRocket,
  FaSeedling,
  FaSpinner,
  FaStar,
  FaSun,
  FaTrophy,
  FaUser,
  FaUserGraduate,
  FaUsers,
  FaVolumeHigh,
  FaVolumeXmark,
  FaXmark,
  FaBars,
  FaCircleCheck,
  FaCircleXmark,
  FaDownload,
  FaArrowRight,
  FaArrowLeft,
  FaArrowUp,
  FaCrown,
  FaLightbulb,
  FaBookmark,
  FaEllipsis,
  FaGear,
  FaBullhorn,
  FaComment,
  FaUserPlus,
  FaClipboardCheck,
  FaChartLine,
  FaHeadset,
  FaMessage,
  FaCircleInfo,
  FaUserPen,
  FaFileContract,
  FaScrewdriverWrench,
  FaFaceSmile,
  FaCapsules,
  FaMicroscope,
  FaCamera,
  FaTrash,
  FaRightToBracket,
  FaRightFromBracket,
  FaIdCard,
  FaKey,
  FaCalendar,
  FaStopwatch,
  FaRotate,
  FaHand,
  FaTriangleExclamation,
  FaDoorOpen,
  FaDoorClosed,
  FaBookOpenReader,
  FaAtom,
  FaImage,
  FaTag,
  FaGaugeHigh,
  FaHandHoldingHeart,
  FaCreditCard,
  FaUnlock,
  FaRoute,
  FaSpellCheck,
  FaEnvelopeCircleCheck,
  FaUserCheck,
  FaGlobe,
  FaLocationDot,
  FaListCheck,
  FaKeyboard,
  FaFlagCheckered,
  FaShare,
  FaFilter,
  FaSquare,
  FaSquareCheck,
  FaFlag,
  FaStop,
  FaCheckDouble,
  FaPaperPlane,
  FaThumbsUp,
  FaShieldHalved,
  FaPlay,
  FaSearch,
  FaXTwitter,
  FaLinkedinIn,
  FaInstagram,
  FaFacebookF,
  FaTelegram,
  FaYoutube,
  FaTiktok,
  FaWhatsapp,
  FaDiscord,
  FaPinterestP,
  FaRedditAlien
} from 'react-icons/fa6';

const ICON_MAP = {
  bell: FaBell,
  'book-open': FaBookOpen,
  brain: FaBrain,
  check: FaCheck,
  'chevron-down': FaChevronDown,
  'chevron-left': FaChevronLeft,
  'chevron-right': FaChevronRight,
  circle: FaCircle,
  clock: FaClock,
  envelope: FaEnvelope,
  'exclamation-triangle': FaTriangleExclamation,
  eye: FaEye,
  'eye-slash': FaEyeSlash,
  'file-lines': FaFileLines,
  'file-pdf': FaFilePdf,
  fire: FaFire,
  flask: FaFlask,
  'graduation-cap': FaGraduationCap,
  heart: FaHeart,
  home: FaHouse,
  'layer-group': FaLayerGroup,
  link: FaLink,
  lock: FaLock,
  'magnifying-glass': FaMagnifyingGlass,
  medal: FaMedal,
  microphone: FaMicrophone,
  'microphone-slash': FaMicrophoneSlash,
  moon: FaMoon,
  'paper-plane': FaPaperPlane,
  'pen-to-square': FaPenToSquare,
  play: FaPlay,
  plus: FaPlus,
  'right-from-bracket': FaRightFromBracket,
  rocket: FaRocket,
  seedling: FaSeedling,
  'shield-halved': FaShieldHalved,
  spinner: FaSpinner,
  star: FaStar,
  sun: FaSun,
  'thumbs-up': FaThumbsUp,
  trophy: FaTrophy,
  user: FaUser,
  'user-graduate': FaUserGraduate,
  users: FaUsers,
  'volume-high': FaVolumeHigh,
  'volume-xmark': FaVolumeXmark,
  xmark: FaXmark,
  bars: FaBars,
  'circle-check': FaCircleCheck,
  'circle-xmark': FaCircleXmark,
  download: FaDownload,
  'arrow-right': FaArrowRight,
  'arrow-left': FaArrowLeft,
  'arrow-up': FaArrowUp,
  crown: FaCrown,
  lightbulb: FaLightbulb,
  bookmark: FaBookmark,
  ellipsis: FaEllipsis,
  gear: FaGear,
  bullhorn: FaBullhorn,
  comment: FaComment,
  'user-plus': FaUserPlus,
  'clipboard-check': FaClipboardCheck,
  'chart-line': FaChartLine,
  headset: FaHeadset,
  message: FaMessage,
  'circle-info': FaCircleInfo,
  'user-pen': FaUserPen,
  'file-contract': FaFileContract,
  'screwdriver-wrench': FaScrewdriverWrench,
  'face-smile': FaFaceSmile,
  capsules: FaCapsules,
  microscope: FaMicroscope,
  camera: FaCamera,
  trash: FaTrash,
  'right-to-bracket': FaRightToBracket,
  'id-card': FaIdCard,
  key: FaKey,
  calendar: FaCalendar,
  stopwatch: FaStopwatch,
  rotate: FaRotate,
  hand: FaHand,
  'door-open': FaDoorOpen,
  'door-closed': FaDoorClosed,
  'book-open-reader': FaBookOpenReader,
  atom: FaAtom,
  image: FaImage,
  tag: FaTag,
  'gauge-high': FaGaugeHigh,
  'hand-holding-heart': FaHandHoldingHeart,
  'credit-card': FaCreditCard,
  unlock: FaUnlock,
  route: FaRoute,
  'spell-check': FaSpellCheck,
  'envelope-circle-check': FaEnvelopeCircleCheck,
  'user-check': FaUserCheck,
  globe: FaGlobe,
  'location-dot': FaLocationDot,
  'list-check': FaListCheck,
  keyboard: FaKeyboard,
  'flag-checkered': FaFlagCheckered,
  share: FaShare,
  filter: FaFilter,
  square: FaSquare,
  'square-check': FaSquareCheck,
  flag: FaFlag,
  stop: FaStop,
  'check-double': FaCheckDouble,
  search: FaSearch,
  'x-twitter': FaXTwitter,
  linkedin: FaLinkedinIn,
  instagram: FaInstagram,
  facebook: FaFacebookF,
  telegram: FaTelegram,
  youtube: FaYoutube,
  tiktok: FaTiktok,
  whatsapp: FaWhatsapp,
  discord: FaDiscord,
  pinterest: FaPinterestP,
  reddit: FaRedditAlien
};

const Icon = memo(function Icon({ name, size, className, ...props }) {
  const Component = ICON_MAP[name];

  if (!Component) return null;

  return createElement(Component, {
    size: size || undefined,
    className: className || undefined,
    ...props
  });
});

export default Icon;
export { ICON_MAP };
