 export {
  FaBars,
  FaBell,
  FaBook,
  FaBookOpen,
  FaBookOpenReader,
  FaBrain,
  FaBullhorn,
  FaBullseye,
  FaCalculator,
  FaCalendarDay,
  FaCapsules,
  FaChartLine,
  FaChartSimple,
  FaCheck,
  FaCircleCheck,
  FaCircleInfo,
  FaCircleXmark,
  FaClipboardCheck,
  FaClock,
  FaComment,
  FaCreditCard,
  FaCrown,
  FaDna,
  FaDownload,
  FaEnvelope,
  FaEnvelopeCircleCheck,
  FaExclamation,
  FaFaceSmile,
  FaFileContract,
  FaFileLines,
  FaFilePdf,
  FaFilePen,
  FaFire,
  FaFlask,
  FaGlobe,
  FaHandHoldingHeart,
  FaHeadset,
  FaHeart,
  FaHospital,
  FaInstagram,
  FaLayerGroup,
  FaLeaf,
  FaLightbulb,
  FaLink,
  FaLinkedinIn,
  FaLocationDot,
  FaLock,
  FaMedal,
  FaMessage,
  FaMicroscope,
  FaMoon,
  FaPen,
  FaPencil,
  FaPenToSquare,
  FaPills,
  FaRightFromBracket,
  FaRightToBracket,
  FaRocket,
  FaRotate,
  FaRoute,
  FaScrewdriverWrench,
  FaShieldHalved,
  FaSpellCheck,
  FaStar,
  FaStarOfLife,
  FaSun,
  FaThumbsUp,
  FaTree,
  FaTriangleExclamation,
  FaTrophy,
  FaUnlock,
  FaUserPen,
  FaUserPlus,
  FaUsers,
  FaVolumeHigh,
  FaVolumeXmark,
  FaXmark,
  FaXTwitter,
FaArrowUp,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaFilter,
  FaSearch,
  FaSpinner,
 } from "react-icons/fa6";

export {
  FaArrowLeft as FaArrowLeftV5,
  FaArrowRight as FaArrowRightV5,
  FaBatteryFull as FaBatteryFullV5,
  FaChevronRight as FaChevronRightV5,
  FaFileAlt as FaFileAltV5,
  FaMousePointer as FaMousePointerV5,
  FaPlay as FaPlayV5,
  FaRandom as FaRandomV5,
  FaSearch as FaSearchV5,
  FaSeedling as FaSeedlingV5,
  FaSignal as FaSignalV5,
  FaWifi as FaWifiV5,
} from "react-icons/fa";
